kind: pipeline
name: default

steps:
  - name: build
    image: klakegg/hugo:alpine
    commands:
      - hugo
  - name: publish
    image: appleboy/drone-git-push
    settings:
      remote_name: origin
      branch: gh-pages
      path: public
