baseURL = "https://gvacaliuc.github.io/"
languageCode = "en-us"
disqusShortname = "gvacaliuc" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Gabe Vacaliuc"
    description = "Gabe Vacaliuc - CS / Stats @ Rice"
    githubUsername = "gvacaliuc"
    profilePic = "https://www.gravatar.com/avatar/d18596782d2a75d869aef7bc22b74764?s=512"
    accent = "orange"
    showBorder = true
    backgroundColor = "white"
    #font = "Raleway" # should match the name on Google Fonts!
    font = "Roboto"
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "python", "R", "java", "c", "cpp"]

[[menu.main]]
    url = "/"
    name = "home"
    weight = 1

[[menu.main]]
    url = "/about"
    name = "about"
    weight = 2

[[menu.main]]
    url = "/posts/"
    name = "posts"
    weight = 3

[[menu.main]]
    url = "/projects/"
    name = "projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:gabe.vacaliuc@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/gvacaliuc/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/gsvaca/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/gabriel-vacaliuc-7aa698131/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/users/4330418/"
    name = "stack-overflow"
    weight = 5
